version: "3.8"

services:
  plantapi:
    image: "plantapi"
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=plantdb;UserId=admin;Password=root;
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plantdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: