version: "3.8"
services:
  plantapi:
    image: tinajassik/plantapi:latest
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=plantdb;UserId=admin;Password=root;
#      - NotificationServerURL=http://notificationserver:5016 #not using it yet, but we might in the future
    depends_on:
      - db
      - notificationserver
    networks:
      - backend
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plantdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  iotbridgeserver:
      image: tinajassik/tcp-server-1:latest
      depends_on:
        - plantapi
      ports:
        - "3014:3014"
        - "5024:5024"
      environment:
        - PLANTAPI_URL=http://plantapi:5000
      networks:
        - backend
  notificationserver:
    image: tinajassik/notification-server:latest
    ports:
      - "5016:5016"  
    networks:
      - backend
networks:
  backend:
volumes:
  postgres_data: