apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: plantapi
  name: plantapi
  namespace: default
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  selector:
    io.kompose.service: plantapi
status:
  loadBalancer: {}
