apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: tcpserver
  name: tcpserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tcpserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-default: "true"
        io.kompose.service: tcpserver
    spec:
      containers:
        - env:
            - name: PLANTAPI_URL
              value: http://plantapi:5000
          image: tinajassik/tcp-server-1:latest
          name: tcpserver
          ports:
            - containerPort: 23
              hostPort: 23
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
