name: Build and Test CI

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - closed
    branches:
      - develop 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup dotnet 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
#      - name: Caching dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.nuget/packages
#          # Look to see if there is a cache hit for the corresponding requirements file
#          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
#          restore-keys:  ${{ runner.os }}-nuget
#      - name: Navigate to project directory
#        run: cd BackEndAPI
#      - name: Install dependencies 
#        run: |
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Microsoft.AspNetCore.Authentication.JwtBearer --version 7.0.13
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Microsoft.AspNetCore.OpenApi --version 7.0.13
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Microsoft.EntityFrameworkCore --version 7.0.13
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Microsoft.EntityFrameworkCore.Design --version 7.0.13
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Npgsql.EntityFrameworkCore.PostgreSQL  --version 7.0.11
#          dotnet add "${{ github.workspace }}/BackEnd/BackEndAPI.csproj" package Swashbuckle.AspNetCore --version 6.4.0
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
        
